# Generated by Django 4.1.7 on 2023-03-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(max_length=2083, upload_to='')),
            ],
        ),
    ]
